### ISSUE TITLE
example issues.

### ISSUE THREAD

**Issue by ciumexan** [farshadjahanmanesh/tipC#2]
Hello, I've looked at it. I cannot run the example, pods installed. 
TipSee-master/Example/TipSee.xcodeproj The file “Pods-TipSee_Example.release.xcconfig” couldn’t be opened because there is no such file. 
TipSee-master/Example/Pods/Pods/Target Support Files/Pods-TipSee_Example/Pods-TipSee_Example.release.xcconfig)

**Comment by fredjahanmanesh** [comment]
hi, pull again and open the TipSee.xcworkspace file. this is what you need to open to run the example.

please let me know if your issue is solved
